name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Atualiza o sistema
        run: apt-get update -y

      - name: Copia workspace
        uses: actions/checkout@v4

      - name: Roda um comando
        run: echo $(ls)