name: Pipeline
on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Copia workspace
        uses: actions/checkout@v4

      - name: Instalacao do Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Executa os testes unitarios
        run: python -m unittest discover -s .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia workspace
        uses: actions/checkout@v4

      - name: Instalacao do Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verifica se o pip está instalado
        run: pip --version

      - name: Instala o pycodestyle e pydocstyle
        run: |
          pip install pycodestyle
          pip install pydocstyle

      - name: Verifica estilo e documentacao do codigo
        run: |
          pycodestyle calc.py
          pydocstyle calc.py